#!/bin/bash
my_date=`date +%s`
fetch https://get.acme.sh -o /root/$my_date\_acme.sh
nginx -c /root/le-server/conf/nginx.conf -p /root/le-server/conf
sh /root/$mydate\_acme.sh
my_domain=`cat /root/le-server/conf/acme_mydomain`
/root/.acme.sh/acme.sh --issue -d $my_domain --webroot /root/le-server/webroot
cp /root/.acme.sh/$my_domain/fullchain.cer /var/etc/cert.crt
cp /root/.acme.sh/$my_domain/$my_domain.key  /var/etc/cert.key
nginx -s quit -c /root/le-server/conf/nginx.conf
nginx -s reload -c /var/etc/nginx-webConfigurator.conf
